name: flutter_home_widget_vignette
description: Demonstrates a basic implementation of an iOS "Home Widget" in Flutter.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  home_widget: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/